# Generated by Django 4.1.3 on 2022-11-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Books Category',
            },
        ),
        migrations.CreateModel(
            name='Book_Deatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('author_name', models.CharField(max_length=50)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='Home/Downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updtated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Book_category_name', to='app.book_category')),
            ],
            options={
                'verbose_name_plural': 'Book_Deatils',
            },
        ),
    ]
