# Generated by Django 4.1.3 on 2022-11-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_category',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_deatils',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, null=True),
        ),
    ]
