# Generated by Django 4.1.3 on 2022-11-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_category_slug_alter_book_deatils_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Category',
            new_name='BookCategory',
        ),
        migrations.RenameModel(
            old_name='Book_Deatils',
            new_name='BookDeatils',
        ),
    ]
